#!/bin/bash
#
# This is a (sometimes significantly) modified version of the excellent build script from https://github.com/markus-perl/ffmpeg-build-script designed for our needs in the Homebridge project.
#
# HOMEPAGE: https://github.com/markus-perl/ffmpeg-build-script
# LICENSE: https://github.com/markus-perl/ffmpeg-build-script/blob/master/LICENSE
#
PROGNAME=$(basename "$0")
SCRIPT_VERSION="1.56-homebridge.2.2.0"
CWD=$(pwd)
PACKAGES="${CWD}/packages"
WORKSPACE="${CWD}/workspace"
CFLAGS="-I${WORKSPACE}/include"
LDFLAGS="-L${WORKSPACE}/lib"
LDEXEFLAGS=""
EXTRALIBS="-ldl -lpthread -lm -lz"
CONFIGURE_OPTIONS=("--disable-doc" "--disable-ffplay" "--disable-ffprobe" "--enable-hardcoded-tables")
NONFREE_AND_GPL=false
LATEST=false
MANPAGES=1
CURRENT_PACKAGE_VERSION=0
AUTOINSTALL="no"
SKIPINSTALL="yes"

# Utilities.
#

# Are we targetting Apple Silicon?
isAppleSilicon() {

  if [[ "${TARGET_ARCH}" == "arm64" && "${TARGET_OS}" == "darwin" ]]; then

    return 0
  fi

  return 1
}

# Are we targetting Linux?
isLinux() {

  if [[ "${TARGET_OS}" == "alpine" || "${TARGET_OS}" == "debian" || "${TARGET_OS}" == "raspbian" || "${OSTYPE}" == "linux-gnu" ]]; then

    return 0
  fi

  return 1
}

# Utility to check if specific options have been added.
contains() {

  local needle="$1"; shift

  for item; do

    [[ "$item" == "$needle" ]] && return 0
  done

  return 1
}

# Prepare architecture and OS-specific options.
#

if [[ "${OSTYPE}" == "darwin"* ]]; then

  TARGET_OS="darwin"
  export CXX=$(which clang++)
elif [ -z "${TARGET_OS}" ]; then

  TARGET_OS=$(uname -s)
fi

if [ -z "${TARGET_ARCH}" ]; then

  TARGET_ARCH=$(uname -m)
fi

# Check for Apple Silicon
if isAppleSilicon; then

  # If arm64 AND darwin (macOS)
  export ARCH=arm64
  export MACOSX_DEPLOYMENT_TARGET=15.0
fi

# On Linux, we disable certain things we don't need or that won't dynamically load correctly.
if isLinux; then

  CONFIGURE_OPTIONS+=("--disable-alsa")
fi

# Speed up the process
# Env Var NUMJOBS overrides automatic detection
if [[ -n "${NUMJOBS}" ]]; then

  MJOBS="${NUMJOBS}"
elif command -v nproc &> /dev/null; then

  MJOBS=$(nproc)
elif [[ -f /proc/cpuinfo ]]; then

  MJOBS=$(grep -c processor /proc/cpuinfo)
elif [[ "${TARGET_OS}" == "darwin" ]]; then

  MJOBS=$(sysctl -n machdep.cpu.thread_count)
  CONFIGURE_OPTIONS+=("--enable-videotoolbox")
  MACOS_LIBTOOL="$(which libtool)" # gnu libtool is installed in this script and need to avoid name conflict
else

  MJOBS=4
fi

make_dir() {

  remove_dir "$1"
  if ! mkdir "$1"; then
    printf "\n Failed to create dir %s" "$1"
    exit 1
  fi
}

remove_dir() {

  if [ -d "$1" ]; then
    rm -r "$1"
  fi
}

clone() {

  # clone url [dirname]

  CLONE_PATH="${PACKAGES}"
  CLONE_NAME="${2:-"${1##*/}"}"
  TARGETDIR="${3:-"${CLONE_NAME%.*}"}"

  if [ ! -d "${CLONE_PATH}/${TARGETDIR}" ]; then

    echo "Cloning from $1 as ${TARGETDIR}"
    git clone -q "$1" "${CLONE_PATH}/${TARGETDIR}"

    EXITCODE=$?
    if [ ${EXITCODE} -ne 0 ]; then

      echo ""
      echo "Failed to download $1. Exitcode ${EXITCODE}. Retrying in 10 seconds"
      sleep 10
      git clone -q "$1" "${CLONE_PATH}/${TARGETDIR}"
    fi

    EXITCODE=$?
    if [ ${EXITCODE} -ne 0 ]; then

      echo ""
      echo "Failed to download $1. Exitcode ${EXITCODE}"
      exit 1
    fi

    echo "... Done"
  else

    echo "${CLONE_NAME} has already downloaded."
  fi

  cd "${CLONE_PATH}/${TARGETDIR}" || (echo "Error has occurred." ; exit 1)
}

download() {

  # download url [filename[dirname]]

  DOWNLOAD_PATH="${PACKAGES}"
  DOWNLOAD_FILE="${2:-"${1##*/}"}"

  if [[ "${DOWNLOAD_FILE}" =~ tar. ]]; then

    TARGETDIR="${DOWNLOAD_FILE%.*}"
    TARGETDIR="${3:-"${TARGETDIR%.*}"}"
  else

    TARGETDIR="${3:-"${DOWNLOAD_FILE%.*}"}"
  fi

  if [ ! -f "${DOWNLOAD_PATH}/${DOWNLOAD_FILE}" ]; then

    echo "Downloading $1 as ${DOWNLOAD_FILE}"
    curl -L --silent -o "${DOWNLOAD_PATH}/${DOWNLOAD_FILE}" "$1"

    EXITCODE=$?
    if [ ${EXITCODE} -ne 0 ]; then

      echo ""
      echo "Failed to download $1. Exitcode ${EXITCODE}. Retrying in 10 seconds"
      sleep 10
      curl -L --silent -o "${DOWNLOAD_PATH}/${DOWNLOAD_FILE}" "$1"
    fi

    EXITCODE=$?
    if [ ${EXITCODE} -ne 0 ]; then

      echo ""
      echo "Failed to download $1. Exitcode ${EXITCODE}"
      exit 1
    fi

    echo "... Done"
  else

    echo "${DOWNLOAD_FILE} has already downloaded."
  fi

  make_dir "${DOWNLOAD_PATH}/${TARGETDIR}"

  if [[ "${DOWNLOAD_FILE}" == *"patch"* ]]; then

    return
  fi

  if [ -n "$3" ]; then

    if ! tar -xvf "${DOWNLOAD_PATH}/${DOWNLOAD_FILE}" -C "${DOWNLOAD_PATH}/${TARGETDIR}" 2>/dev/null >/dev/null; then

      echo "Failed to extract ${DOWNLOAD_FILE}"
      exit 1
    fi
  else

    if ! tar -xvf "${DOWNLOAD_PATH}/${DOWNLOAD_FILE}" -C "${DOWNLOAD_PATH}/${TARGETDIR}" --strip-components 1 2>/dev/null >/dev/null; then
      echo "Failed to extract ${DOWNLOAD_FILE}"
      exit 1
    fi
  fi

  echo "Extracted ${DOWNLOAD_FILE}"

  cd "${DOWNLOAD_PATH}/${TARGETDIR}" || (echo "Error has occurred."; exit 1)
}

execute() {

  echo "$ $*"

  OUTPUT=$("$@" 2>&1)

  # shellcheck disable=SC2181
  if [ $? -ne 0 ]; then
    echo "${OUTPUT}"
    echo ""
    echo "Failed to Execute $*" >&2
    exit 1
  fi
}

build() {

  echo ""
  echo "building $1 - version $2"
  echo "======================="
  CURRENT_PACKAGE_VERSION=$2

  if [ -f "${PACKAGES}/$1.done" ]; then

    if grep -Fx "$2" "${PACKAGES}/$1.done" >/dev/null; then

      echo "$1 version $2 already built. Remove ${PACKAGES}/$1.done lockfile to rebuild it."
      return 1
    elif ${LATEST}; then

      echo "$1 is outdated and will be rebuilt with latest version $2"
      return 0
    else

      echo "$1 is outdated, but will not be rebuilt. Pass in --latest to rebuild it or remove ${PACKAGES}/$1.done lockfile."
      return 1
    fi
  fi

  return 0
}

command_exists() {

  if ! [[ -x $(command -v "$1") ]]; then

    return 1
  fi

  return 0
}

library_exists() {

  if ! [[ -x $(pkg-config --exists --print-errors "$1" 2>&1 >/dev/null) ]]; then

    return 1
  fi

  return 0
}

build_done() {

  echo "$2" >"${PACKAGES}/$1.done"
}

verify_binary_type() {

  if ! command_exists "file"; then

    return
  fi

  BINARY_TYPE=$(file "${WORKSPACE}/bin/ffmpeg" | sed -n 's/^.*\:\ \(.*$\)/\1/p')
  echo ""
  case ${BINARY_TYPE} in

    "Mach-O 64-bit executable arm64")
      echo "Successfully built Apple Silicon (M1) for ${OSTYPE}: ${BINARY_TYPE}"
      ;;

    *)
      echo "Successfully built binary for ${OSTYPE}: ${BINARY_TYPE}"
      ;;

  esac
}

cleanup() {

  remove_dir "${PACKAGES}"
  remove_dir "${WORKSPACE}"
  echo "Cleanup done."
  echo ""
}

usage() {

  echo "Usage: ${PROGNAME} [OPTIONS]"
  echo "Options:"
  echo "  -h, --help                     Display usage information"
  echo "      --version                  Display version information"
  echo "  -b, --build                    Starts the build process"
  echo "      --enable-gpl-and-non-free  Enable GPL and non-free codecs  - https://ffmpeg.org/legal.html"
  echo "  -c, --cleanup                  Remove all working dirs"
  echo "      --latest                   Build latest version of dependencies if newer available"
  echo "      --full-static              Build a full static FFmpeg binary (eg. glibc, pthreads etc...) **only Linux**"
  echo "                                 Note: Because of the NSS (Name Service Switch), glibc does not recommend static links."
  echo ""
}

echo "ffmpeg-build-script v${SCRIPT_VERSION}"
echo "========================="
echo ""
echo "Building for ${OSTYPE} (${TARGET_OS}-${TARGET_ARCH}) on $(uname -m)"
echo ""

while (($# > 0)); do

  case $1 in

    -h | --help)
      usage
      exit 0
      ;;

    --version)
      echo "${SCRIPT_VERSION}"
      exit 0
      ;;

    -*)
      if [[ "$1" == "--build" || "$1" =~ '-b' ]]; then

        bflag='-b'
      fi

      if [[ "$1" == "--enable-gpl-and-non-free" ]]; then

        CONFIGURE_OPTIONS+=("--enable-nonfree" "--enable-gpl")
        NONFREE_AND_GPL=true
      fi

      if [[ "$1" == "--cleanup" || "$1" =~ '-c' && ! "$1" =~ '--' ]]; then

        cflag='-c'
        cleanup
      fi

      if [[ "$1" == "--full-static" ]]; then

        if [[ "${TARGET_OS}" == "darwin" ]]; then

          echo "Error: A full static binary can only be build on Linux."
          exit 1
        fi

        LDEXEFLAGS="-static"
      fi

      if [[ "$1" == "--latest" ]]; then

        LATEST=true
      fi

      shift
      ;;

    *)
      usage
      exit 1
      ;;

  esac
done

if [ -z "$bflag" ]; then

  if [ -z "$cflag" ]; then

    usage

    exit 1
  fi

  exit 0
fi

echo "Using ${MJOBS} make jobs simultaneously."

if ${NONFREE_AND_GPL}; then

  echo "With GPL and non-free codecs"
fi

if [ -n "${LDEXEFLAGS}" ]; then

  echo "Start the build in full static mode."
fi

mkdir -p "${PACKAGES}"
mkdir -p "${WORKSPACE}"

export PATH="${WORKSPACE}/bin:${PATH}"

PKG_CONFIG_PATH=""

if [[ "${TARGET_OS}" == "raspbian" ]]; then

  PKG_CONFIG_PATH+="${WORKSPACE}/opt/vc/lib/pkgconfig:"
fi

PKG_CONFIG_PATH+="${WORKSPACE}/lib/pkgconfig:/usr/local/lib/${TARGET_ARCH}-${OSTYPE}/pkgconfig:/usr/local/lib/pkgconfig"
PKG_CONFIG_PATH+=":/usr/local/share/pkgconfig:/usr/lib/${TARGET_ARCH}-${OSTYPE}/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig:/usr/lib64/pkgconfig"
export PKG_CONFIG_PATH

echo "Package config path: ${PKG_CONFIG_PATH}"

if ! command_exists "make"; then

  echo "make not installed."

  exit 1
fi

if ! command_exists "g++"; then

  echo "g++ not installed."

  exit 1
fi

if ! command_exists "curl"; then

  echo "curl not installed."

  exit 1
fi

if ! command_exists "cargo"; then

  echo "cargo not installed. rav1e encoder will not be available."
fi

if ! command_exists "python3"; then

  echo "python3 command not found. Lv2 filter and dav1d decoder will not be available."
fi

##
## build tools
##

# Check for Raspberry Pi
if [[ "${TARGET_OS}" == "raspbian" ]]; then

  echo "Installing Raspberry Pi-specific development tools and configuring for Raspberry Pi-specific codecs."

  if build "rpi-userland" "latest"; then

    clone "https://github.com/raspberrypi/userland.git" "rpi-userland"

    # Native compile on the Raspberry Pi
    mkdir -p build/raspberry
    cd build/raspberry
    # VMCS_INSTALL_PREFIX="${WORKSPACE}"
    execute cmake -DLIBRARY_TYPE=STATIC -DENABLE_SHARED=OFF -DBUILD_SHARED_LIBS=OFF -DCMAKE_BUILD_TYPE=Release -DARM64=off -DCMAKE_TOOLCHAIN_FILE=../../makefiles/cmake/toolchains/arm-linux-gnueabihf.cmake ../..
    execute make -j ${MJOBS}
    execute make install DESTDIR="${WORKSPACE}"

    build_done "rpi-userland" "latest"
  fi

  CFLAGS+=" -I${WORKSPACE}/opt/vc/include/IL"
  LDFLAGS+=" -L${WORKSPACE}/opt/vc/lib"

  # CONFIGURE_OPTIONS+=("--enable-mmal" "--enable-omx-rpi")
  CONFIGURE_OPTIONS+=("--enable-omx-rpi")
fi

if ! isLinux; then

  if build "giflib" "5.2.1"; then

    download "https://downloads.sourceforge.net/project/giflib/giflib-${CURRENT_PACKAGE_VERSION}.tar.gz"

    if [[ "${TARGET_OS}" == "darwin" ]]; then

      download "https://sourceforge.net/p/giflib/bugs/_discuss/thread/4e811ad29b/c323/attachment/Makefile.patch"
      execute patch -p0 --forward "${PACKAGES}/giflib-5.2.1/Makefile" "${PACKAGES}/Makefile.patch" || true
    fi
    #multicore build disabled for this library
    execute make
    execute make PREFIX="${WORKSPACE}" install

    build_done "giflib" "${CURRENT_PACKAGE_VERSION}"
  fi

  if build "pkg-config" "0.29.2"; then

    download "https://pkgconfig.freedesktop.org/releases/pkg-config-${CURRENT_PACKAGE_VERSION}.tar.gz"

    execute ./configure CFLAGS="-g -O2 -Wno-int-conversion" --silent --prefix="${WORKSPACE}" --with-pc-path="${WORKSPACE}/lib/pkgconfig:/usr/lib/${TARGET_ARCH}-${OSTYPE}/pkgconfig" --with-internal-glib
    execute make -j ${MJOBS}
    execute make install

    build_done "pkg-config" "${CURRENT_PACKAGE_VERSION}"
  fi

  if build "yasm" "1.3.0"; then

    download "https://github.com/yasm/yasm/releases/download/v1.3.0/yasm-${CURRENT_PACKAGE_VERSION}.tar.gz"

    execute ./configure --prefix="${WORKSPACE}"
    execute make -j ${MJOBS}
    execute make install

    build_done "yasm" "${CURRENT_PACKAGE_VERSION}"
  fi

  if build "nasm" "2.16.01"; then

    download "https://www.nasm.us/pub/nasm/releasebuilds/2.16.01/nasm-${CURRENT_PACKAGE_VERSION}.tar.xz"

    execute ./configure --prefix="${WORKSPACE}" --disable-shared --enable-static
    execute make -j ${MJOBS}
    execute make install

    build_done "nasm" "${CURRENT_PACKAGE_VERSION}"
  fi

  if build "zlib" "1.3.1"; then

    download "https://zlib.net/fossils/zlib-${CURRENT_PACKAGE_VERSION}.tar.gz"

    execute ./configure --static --prefix="${WORKSPACE}"
    execute make -j ${MJOBS}
    execute make install

    build_done "zlib" "${CURRENT_PACKAGE_VERSION}"
  fi

  if build "m4" "1.4.19"; then

    download "https://ftp.gnu.org/gnu/m4/m4-${CURRENT_PACKAGE_VERSION}.tar.gz"

    execute ./configure --prefix="${WORKSPACE}"
    execute make -j ${MJOBS}
    execute make install

    build_done "m4" "${CURRENT_PACKAGE_VERSION}"
  fi

  if build "autoconf" "2.72"; then

    download "https://ftp.gnu.org/gnu/autoconf/autoconf-${CURRENT_PACKAGE_VERSION}.tar.gz"

    execute ./configure --prefix="${WORKSPACE}"
    execute make -j ${MJOBS}
    execute make install

    build_done "autoconf" "${CURRENT_PACKAGE_VERSION}"
  fi

  if build "automake" "1.17"; then

    download "https://ftp.gnu.org/gnu/automake/automake-${CURRENT_PACKAGE_VERSION}.tar.gz"

    execute ./configure --prefix="${WORKSPACE}"
    execute make -j ${MJOBS}
    execute make install

    build_done "automake" "${CURRENT_PACKAGE_VERSION}"
  fi
fi

if build "libtool" "2.4.7"; then

  download "http://ftp.gnu.org/gnu/libtool/libtool-${CURRENT_PACKAGE_VERSION}.tar.gz"

  execute ./configure --prefix="${WORKSPACE}" --enable-static --disable-shared
  execute make -j ${MJOBS}
  execute make install

  build_done "libtool" "${CURRENT_PACKAGE_VERSION}"
fi

if ${NONFREE_AND_GPL}; then

  if ! isLinux; then

    if build "gettext" "0.22.5"; then

      download "https://ftpmirror.gnu.org/gettext/gettext-${CURRENT_PACKAGE_VERSION}.tar.gz"

      execute ./configure --prefix="${WORKSPACE}" --enable-static --disable-shared
      execute make -j $MJOBS
      execute make install

      build_done "gettext" "${CURRENT_PACKAGE_VERSION}"
    fi

    if build "openssl" "3.5.0"; then

      download "https://github.com/openssl/openssl/archive/refs/tags/openssl-${CURRENT_PACKAGE_VERSION}.tar.gz" "openssl-${CURRENT_PACKAGE_VERSION}.tar.gz"

      execute ./Configure --prefix="${WORKSPACE}" --openssldir="${WORKSPACE}" --libdir="lib" --with-zlib-include="${WORKSPACE}"/include/ --with-zlib-lib="${WORKSPACE}"/lib no-shared zlib
      execute make -j $MJOBS
      execute make install_sw

      build_done "openssl" "${CURRENT_PACKAGE_VERSION}"
    fi
  fi

  CONFIGURE_OPTIONS+=("--enable-openssl")
else

  if build "gmp" "6.3.0"; then

    download "https://ftp.gnu.org/gnu/gmp/gmp-${CURRENT_PACKAGE_VERSION}.tar.xz"

    execute ./configure --prefix="${WORKSPACE}" --disable-shared --enable-static
    execute make -j ${MJOBS}
    execute make install

    build_done "gmp" "${CURRENT_PACKAGE_VERSION}"
  fi

  if build "nettle" "3.10"; then

    download "https://ftp.gnu.org/gnu/nettle/nettle-${CURRENT_PACKAGE_VERSION}.tar.gz"

    execute ./configure --prefix="${WORKSPACE}" --disable-shared --enable-static --disable-openssl --disable-documentation --libdir="${WORKSPACE}"/lib CPPFLAGS="${CFLAGS}" LDFLAGS="${LDFLAGS}"
    execute make -j ${MJOBS}
    execute make install

    build_done "nettle" "${CURRENT_PACKAGE_VERSION}"
  fi

  if [[ ! ${TARGET_ARCH} == 'arm64' ]]; then

    if build "gnutls" "3.8.5"; then

      download "https://www.gnupg.org/ftp/gcrypt/gnutls/v3.8/gnutls-${CURRENT_PACKAGE_VERSION}.tar.xz"

      execute ./configure --prefix="${WORKSPACE}" --disable-shared --enable-static --disable-doc --disable-tools --disable-cxx --disable-tests --disable-gtk-doc-html --disable-libdane --disable-nls --enable-local-libopts --disable-guile --with-included-libtasn1 --with-included-unistring --without-p11-kit CPPFLAGS="${CFLAGS}" LDFLAGS="${LDFLAGS}"
      execute make -j ${MJOBS}
      execute make install

      build_done "gnutls" "${CURRENT_PACKAGE_VERSION}"
    fi

    # CONFIGURE_OPTIONS+=("--enable-gmp" "--enable-gnutls")
  fi
fi

if ! isLinux; then

  if build "cmake" "3.31.7"; then

    download "https://github.com/Kitware/CMake/releases/download/v${CURRENT_PACKAGE_VERSION}/cmake-${CURRENT_PACKAGE_VERSION}.tar.gz"

    execute ./configure --prefix="${WORKSPACE}" --parallel="${MJOBS}" -- -DCMAKE_USE_OPENSSL=OFF
    execute make -j ${MJOBS}
    execute make install

    build_done "cmake" "${CURRENT_PACKAGE_VERSION}"
  fi
fi

##
## video library
##

if command_exists "python3"; then

  # dav1d needs meson and ninja along with nasm to be built
  if ! isLinux; then

    if command_exists "pip3"; then

      # meson and ninja can be installed via pip3
      execute /usr/bin/pip3 install pip setuptools --quiet --upgrade --no-cache-dir --disable-pip-version-check

      for r in meson ninja; do

        if ! command_exists ${r}; then

          execute /usr/bin/pip3 install ${r} --quiet --upgrade --no-cache-dir --disable-pip-version-check
        fi

        export PATH=${PATH}:~/Library/Python/3.9/bin
      done
    fi
  fi

  if command_exists "meson"; then

    if build "dav1d" "1.5.1"; then

      download "https://code.videolan.org/videolan/dav1d/-/archive/1.1.0/dav1d-${CURRENT_PACKAGE_VERSION}.tar.gz"

      make_dir build

      CFLAGSBACKUP=${CFLAGS}
      if isAppleSilicon; then

        export CFLAGS="-arch arm64"
      fi

      execute meson build --prefix="${WORKSPACE}" --buildtype=release --default-library=static --libdir="${WORKSPACE}"/lib
      execute ninja -C build
      execute ninja -C build install

      if isAppleSilicon; then

        export CFLAGS=${CFLAGSBACKUP}
      fi

      build_done "dav1d" "${CURRENT_PACKAGE_VERSION}"
    fi

    CONFIGURE_OPTIONS+=("--enable-libdav1d")
  fi
fi

if build "svtav1" "3.0.2"; then

  # Last known working commit which passed CI Tests from HEAD branch
  download "https://gitlab.com/AOMediaCodec/SVT-AV1/-/archive/v${CURRENT_PACKAGE_VERSION}/SVT-AV1-v${CURRENT_PACKAGE_VERSION}.tar.gz" "svtav1-${CURRENT_PACKAGE_VERSION}.tar.gz"

  cd "${PACKAGES}"/svtav1-${CURRENT_PACKAGE_VERSION}//Build/linux || exit
  execute cmake -DCMAKE_INSTALL_PREFIX="${WORKSPACE}" -DENABLE_SHARED=off -DBUILD_SHARED_LIBS=OFF ../.. -G"Unix Makefiles" -DCMAKE_BUILD_TYPE=Release
  execute make -j ${MJOBS}
  execute make install
  execute cp SvtAv1Enc.pc "${WORKSPACE}/lib/pkgconfig/"

  build_done "svtav1" "${CURRENT_PACKAGE_VERSION}"
fi

CONFIGURE_OPTIONS+=("--enable-libsvtav1")

if command_exists "cargo"; then

  if [[ ! "${SKIPRAV1E}" == "yes" ]]; then

    if build "rav1e" "0.8.0"; then

      download "https://github.com/xiph/rav1e/archive/refs/tags/v${CURRENT_PACKAGE_VERSION}.tar.gz"

      execute cargo install cargo-c
      export RUSTFLAGS="-C target-cpu=native"
      execute cargo cinstall --prefix="${WORKSPACE}" --library-type=staticlib --crt-static --release

      build_done "rav1e" "${CURRENT_PACKAGE_VERSION}"
    fi

    CONFIGURE_OPTIONS+=("--enable-librav1e")
  fi
fi

if ${NONFREE_AND_GPL}; then

  if build "x264" "b35605ac"; then

    download "https://code.videolan.org/videolan/x264/-/archive/${CURRENT_PACKAGE_VERSION}/x264-${CURRENT_PACKAGE_VERSION}.tar.gz" "x264-${CURRENT_PACKAGE_VERSION}.tar.gz"
    cd "${PACKAGES}"/x264-${CURRENT_PACKAGE_VERSION} || exit

    if isLinux; then
      execute ./configure --prefix="${WORKSPACE}" --enable-static --enable-pic CXXFLAGS="-fPIC ${CXXFLAGS}"
    else
      execute ./configure --prefix="${WORKSPACE}" --enable-static --enable-pic
    fi

    execute make -j $MJOBS
    execute make install
    execute make install-lib-static

    build_done "x264" "${CURRENT_PACKAGE_VERSION}"
  fi

  CONFIGURE_OPTIONS+=("--enable-libx264")
fi

# 32-bit ARM platforms like Raspberry Pi don't build x265 cleanly.
if ${NONFREE_AND_GPL} && [[ ! "${TARGET_ARCH}" == "armv7l" ]] ; then

  if build "x265" "4.1"; then

    download "https://bitbucket.org/multicoreware/x265_git/downloads/x265_${CURRENT_PACKAGE_VERSION}.tar.gz" "x265-${CURRENT_PACKAGE_VERSION}.tar.gz" # This is actually 3.4 if looking at x265Version.txt

    cd build/linux || exit
    rm -rf 8bit 10bit 12bit 2>/dev/null
    mkdir -p 8bit 10bit 12bit

    cd 12bit || exit
    execute cmake ../../../source -DCMAKE_INSTALL_PREFIX="${WORKSPACE}" -DENABLE_SHARED=OFF -DBUILD_SHARED_LIBS=OFF -DHIGH_BIT_DEPTH=ON -DENABLE_HDR10_PLUS=ON -DEXPORT_C_API=OFF -DENABLE_CLI=OFF -DMAIN12=ON
    execute make -j ${MJOBS}

    cd ../10bit || exit
    execute cmake ../../../source -DCMAKE_INSTALL_PREFIX="${WORKSPACE}" -DENABLE_SHARED=OFF -DBUILD_SHARED_LIBS=OFF -DHIGH_BIT_DEPTH=ON -DENABLE_HDR10_PLUS=ON -DEXPORT_C_API=OFF -DENABLE_CLI=OFF
    execute make -j ${MJOBS}

    cd ../8bit || exit
    ln -sf ../10bit/libx265.a libx265_main10.a
    ln -sf ../12bit/libx265.a libx265_main12.a
    execute cmake ../../../source -DCMAKE_INSTALL_PREFIX="${WORKSPACE}" -DENABLE_SHARED=OFF -DBUILD_SHARED_LIBS=OFF -DEXTRA_LIB="x265_main10.a;x265_main12.a;-ldl" -DEXTRA_LINK_FLAGS=-L. -DLINKED_10BIT=ON -DLINKED_12BIT=ON
    execute make -j ${MJOBS}

    mv libx265.a libx265_main.a

    if [[ "${TARGET_OS}" == "darwin" ]]; then

      execute "${MACOS_LIBTOOL}" -static -o libx265.a libx265_main.a libx265_main10.a libx265_main12.a 2>/dev/null
    else

      execute ar -M <<EOF
CREATE libx265.a
ADDLIB libx265_main.a
ADDLIB libx265_main10.a
ADDLIB libx265_main12.a
SAVE
END
EOF
    fi

    execute make install

    if [ -n "${LDEXEFLAGS}" ]; then

      sed -i.backup 's/-lgcc_s/-lgcc_eh/g' "${WORKSPACE}/lib/pkgconfig/x265.pc" # The -i.backup is intended and required on macOS: https://stackoverflow.com/questions/5694228/sed-in-place-flag-that-works-both-on-mac-bsd-and-linux
    fi

    build_done "x265" "${CURRENT_PACKAGE_VERSION}"
  fi

  CONFIGURE_OPTIONS+=("--enable-libx265")
fi

if [[ ! "${TARGET_ARCH}" == "arm"* ]]; then

  if build "libvpx" "1.15.2"; then

    download "https://github.com/webmproject/libvpx/archive/refs/tags/v${CURRENT_PACKAGE_VERSION}.tar.gz" "libvpx-${CURRENT_PACKAGE_VERSION}.tar.gz"

    if [[ "${TARGET_OS}" == "darwin" ]]; then

      echo "Applying Darwin patch"
      sed "s/,--version-script//g" build/make/Makefile > build/make/Makefile.patched
      sed "s/-Wl,--no-undefined -Wl,-soname/-Wl,-undefined,error -Wl,-install_name/g" build/make/Makefile.patched > build/make/Makefile
    fi

    execute ./configure --prefix="${WORKSPACE}" --disable-unit-tests --disable-shared --disable-examples --as=yasm --enable-vp9-highbitdepth
    execute make -j ${MJOBS}
    execute make install

    build_done "libvpx" "${CURRENT_PACKAGE_VERSION}"
  fi

  CONFIGURE_OPTIONS+=("--enable-libvpx")
fi

if ${NONFREE_AND_GPL}; then

  if ! isLinux; then

    if build "xvidcore" "1.3.7"; then

      download "https://downloads.xvid.com/downloads/xvidcore-${CURRENT_PACKAGE_VERSION}.tar.gz"

      cd build/generic || exit
      execute ./configure --prefix="${WORKSPACE}" --disable-shared --enable-static
      execute make -j ${MJOBS}
      execute make install

      if [[ -f ${WORKSPACE}/lib/libxvidcore.4.dylib ]]; then
        execute rm "${WORKSPACE}/lib/libxvidcore.4.dylib"
      fi

      if [[ -f ${WORKSPACE}/lib/libxvidcore.so ]]; then
        execute rm "${WORKSPACE}"/lib/libxvidcore.so*
      fi

      build_done "xvidcore" "${CURRENT_PACKAGE_VERSION}"
    fi
  fi

  CONFIGURE_OPTIONS+=("--enable-libxvid")
fi

if ${NONFREE_AND_GPL}; then

  if build "vid_stab" "1.1.1"; then

    download "https://github.com/georgmartius/vid.stab/archive/v${CURRENT_PACKAGE_VERSION}.tar.gz" "vid.stab-${CURRENT_PACKAGE_VERSION}.tar.gz"

    execute cmake -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX="${WORKSPACE}" -DUSE_OMP=OFF -DENABLE_SHARED=off .
    execute make
    execute make install

    build_done "vid_stab" "${CURRENT_PACKAGE_VERSION}"
  fi

  CONFIGURE_OPTIONS+=("--enable-libvidstab")
fi

if [[ ! "${TARGET_ARCH}" == "arm"* ]]; then

  if build "av1" "10aece4157eb79315da205f39e19bf6ab3ee30d0"; then

    #  10aece4157eb79315da205f39e19bf6ab3ee30d0 == v3.12.1
    download "https://aomedia.googlesource.com/aom/+archive/${CURRENT_PACKAGE_VERSION}.tar.gz" "av1.tar.gz" "av1"
    make_dir "$PACKAGES"/aom_build
    cd "$PACKAGES"/aom_build || exit
    if isAppleSilicon; then

      execute cmake -DENABLE_TESTS=0 -DENABLE_EXAMPLES=0 -DCMAKE_INSTALL_PREFIX="${WORKSPACE}" -DCMAKE_INSTALL_LIBDIR=lib -DCONFIG_RUNTIME_CPU_DETECT=0 "$PACKAGES"/av1
    else

      execute cmake -DENABLE_TESTS=0 -DENABLE_EXAMPLES=0 -DCMAKE_INSTALL_PREFIX="${WORKSPACE}" -DCMAKE_INSTALL_LIBDIR=lib "$PACKAGES"/av1
    fi

    execute make -j ${MJOBS}
    execute make install

    build_done "av1" "${CURRENT_PACKAGE_VERSION}"
  fi

  CONFIGURE_OPTIONS+=("--enable-libaom")
fi

if build "zimg" "3.0.5"; then

  download "https://github.com/sekrit-twc/zimg/archive/refs/tags/release-${CURRENT_PACKAGE_VERSION}.tar.gz" "zimg-${CURRENT_PACKAGE_VERSION}.tar.gz" "zimg"

  cd zimg-release-${CURRENT_PACKAGE_VERSION} || exit
  execute "${WORKSPACE}/bin/libtoolize" -i -f -q
  execute ./autogen.sh --prefix="${WORKSPACE}"
  execute ./configure --prefix="${WORKSPACE}" --enable-static --disable-shared
  execute make -j ${MJOBS}
  execute make install

  build_done "zimg" "${CURRENT_PACKAGE_VERSION}"
fi

CONFIGURE_OPTIONS+=("--enable-libzimg")

##
## audio library
##

if command_exists "python3"; then

  if command_exists "meson"; then

    if build "lv2" "1.18.10"; then

      download "https://lv2plug.in/spec/lv2-${CURRENT_PACKAGE_VERSION}.tar.xz" "lv2-${CURRENT_PACKAGE_VERSION}.tar.xz"

      execute meson build --prefix="${WORKSPACE}" --buildtype=release --default-library=static --libdir="${WORKSPACE}"/lib
      execute ninja -C build
      execute ninja -C build install

      build_done "lv2" "${CURRENT_PACKAGE_VERSION}"
    fi

    if build "waflib" "b600c92"; then

      download "https://gitlab.com/drobilla/autowaf/-/archive/${CURRENT_PACKAGE_VERSION}/autowaf-${CURRENT_PACKAGE_VERSION}.tar.gz" "autowaf.tar.gz"

      build_done "waflib" "${CURRENT_PACKAGE_VERSION}"
    fi

    if build "serd" "0.32.2"; then

      download "https://gitlab.com/drobilla/serd/-/archive/v${CURRENT_PACKAGE_VERSION}/serd-v${CURRENT_PACKAGE_VERSION}.tar.gz" "serd-v${CURRENT_PACKAGE_VERSION}.tar.gz"

      execute meson build --prefix="${WORKSPACE}" --buildtype=release --default-library=static --libdir="${WORKSPACE}"/lib
      execute ninja -C build
      execute ninja -C build install

      build_done "serd" "${CURRENT_PACKAGE_VERSION}"
    fi

    if ! isLinux; then

      if build "pcre" "8.45"; then

        download "https://downloads.sourceforge.net/project/pcre/pcre/${CURRENT_PACKAGE_VERSION}/pcre-${CURRENT_PACKAGE_VERSION}.tar.gz" "pcre-${CURRENT_PACKAGE_VERSION}.tar.gz"

        execute ./configure --prefix="${WORKSPACE}" --disable-shared --enable-static
        execute make -j ${MJOBS}
        execute make install

        build_done "pcre" "${CURRENT_PACKAGE_VERSION}"
      fi
    fi

    if build "zix" "0.6.2"; then

      download "https://gitlab.com/drobilla/zix/-/archive/v${CURRENT_PACKAGE_VERSION}/zix-v${CURRENT_PACKAGE_VERSION}.tar.gz" "zix-v${CURRENT_PACKAGE_VERSION}.tar.gz"

      execute meson setup build --prefix="${WORKSPACE}" --buildtype=release --default-library=static --libdir="${WORKSPACE}"/lib
      cd build || exit
      execute meson configure -Dc_args="-march=native" -Dprefix="${WORKSPACE}" -Dlibdir="${WORKSPACE}"/lib
      execute meson compile
      execute meson install

      build_done "zix" "${CURRENT_PACKAGE_VERSION}"
    fi

    if build "sord" "0.16.16"; then

      download "https://gitlab.com/drobilla/sord/-/archive/v${CURRENT_PACKAGE_VERSION}/sord-v${CURRENT_PACKAGE_VERSION}.tar.gz" "sord-v${CURRENT_PACKAGE_VERSION}.tar.gz"

      execute meson build --prefix="${WORKSPACE}" --buildtype=release --default-library=static --libdir="${WORKSPACE}"/lib
      execute ninja -C build
      execute ninja -C build install

      build_done "sord" "${CURRENT_PACKAGE_VERSION}"
    fi

    if build "sratom" "0.6.16"; then

      download "https://gitlab.com/lv2/sratom/-/archive/v${CURRENT_PACKAGE_VERSION}/sratom-v${CURRENT_PACKAGE_VERSION}.tar.gz" "sratom-v${CURRENT_PACKAGE_VERSION}.tar.gz"

      execute meson build --prefix="${WORKSPACE}" --buildtype=release --default-library=static --libdir="${WORKSPACE}"/lib
      execute ninja -C build
      execute ninja -C build install

      build_done "sratom" "${CURRENT_PACKAGE_VERSION}"
    fi

    if build "lilv" "0.24.20"; then

      download "https://gitlab.com/lv2/lilv/-/archive/v${CURRENT_PACKAGE_VERSION}/lilv-v${CURRENT_PACKAGE_VERSION}.tar.gz" "lilv-v${CURRENT_PACKAGE_VERSION}.tar.gz"

      execute meson build --prefix="${WORKSPACE}" --buildtype=release --default-library=static --libdir="${WORKSPACE}"/lib -Dcpp_std=c++11
      execute ninja -C build
      execute ninja -C build install

      build_done "lilv" "${CURRENT_PACKAGE_VERSION}"
    fi

    CFLAGS+=" -I${WORKSPACE}/include/lilv-0"

    CONFIGURE_OPTIONS+=("--enable-lv2")
  fi
fi

if ! isLinux; then

  if build "opencore" "0.1.6"; then

    download "https://downloads.sourceforge.net/project/opencore-amr/opencore-amr/opencore-amr-${CURRENT_PACKAGE_VERSION}.tar.gz"

    execute ./configure --prefix="${WORKSPACE}" --disable-shared --enable-static
    execute make -j ${MJOBS}
    execute make install

    build_done "opencore" "${CURRENT_PACKAGE_VERSION}"
  fi
fi

CONFIGURE_OPTIONS+=("--enable-libopencore_amrnb" "--enable-libopencore_amrwb")

if ! isLinux; then

  if build "lame" "3.100"; then

    download "https://downloads.sourceforge.net/project/lame/lame/3.100/lame-${CURRENT_PACKAGE_VERSION}.tar.gz"

    execute ./configure --prefix="${WORKSPACE}" --disable-shared --enable-static
    execute make -j ${MJOBS}
    execute make install

    build_done "lame" "${CURRENT_PACKAGE_VERSION}"
  fi
fi

CONFIGURE_OPTIONS+=("--enable-libmp3lame")

if build "opus" "1.5.2"; then

  download "https://downloads.xiph.org/releases/opus/opus-${CURRENT_PACKAGE_VERSION}.tar.gz"

  execute ./configure --prefix="${WORKSPACE}" --disable-shared --enable-static
  execute make -j ${MJOBS}
  execute make install

  build_done "opus" "${CURRENT_PACKAGE_VERSION}"
fi

CONFIGURE_OPTIONS+=("--enable-libopus")

if build "speex" "1.2.1"; then

  download "https://ftp.osuosl.org/pub/xiph/releases/speex/speex-${CURRENT_PACKAGE_VERSION}.tar.gz"

  execute ./configure --prefix="${WORKSPACE}" --disable-shared --enable-static
  execute make -j ${MJOBS}
  execute make install

  build_done "speex" "${CURRENT_PACKAGE_VERSION}"
fi

CONFIGURE_OPTIONS+=("--enable-libspeex")

if ! isLinux; then

  if build "libogg" "1.3.5"; then

    download "https://ftp.osuosl.org/pub/xiph/releases/ogg/libogg-${CURRENT_PACKAGE_VERSION}.tar.xz"

    execute ./configure --prefix="${WORKSPACE}" --disable-shared --enable-static
    execute make -j ${MJOBS}
    execute make install

    build_done "libogg" "${CURRENT_PACKAGE_VERSION}"
  fi

  if build "libvorbis" "1.3.7"; then

    download "https://ftp.osuosl.org/pub/xiph/releases/vorbis/libvorbis-${CURRENT_PACKAGE_VERSION}.tar.gz"

    if [[ "${TARGET_OS}" == "darwin" ]]; then

      sed -i.backup 's/-force_cpusubtype_ALL //g' configure # The -i.backup is intended and required on macOS: https://stackoverflow.com/questions/5694228/sed-in-place-flag-that-works-both-on-mac-bsd-and-linux
    fi

    execute ./configure --prefix="${WORKSPACE}" --with-ogg-libraries="${WORKSPACE}"/lib --with-ogg-includes="${WORKSPACE}"/include/ --enable-static --disable-shared --disable-oggtest
    execute make -j ${MJOBS}
    execute make install

    build_done "libvorbis" "${CURRENT_PACKAGE_VERSION}"
  fi
fi

CONFIGURE_OPTIONS+=("--enable-libvorbis")

if ! isLinux; then

  if build "libtheora" "1.2.0"; then

    download "https://ftp.osuosl.org/pub/xiph/releases/theora/libtheora-${CURRENT_PACKAGE_VERSION}.tar.gz"

    execute ./configure --prefix="${WORKSPACE}" --with-ogg-libraries="${WORKSPACE}"/lib --with-ogg-includes="${WORKSPACE}"/include/ --with-vorbis-libraries="${WORKSPACE}"/lib --with-vorbis-includes="${WORKSPACE}"/include/ --enable-static --disable-shared --disable-oggtest --disable-vorbistest --disable-examples --disable-spec
    execute make -j ${MJOBS}
    execute make install

    build_done "libtheora" "${CURRENT_PACKAGE_VERSION}"
  fi
fi

CONFIGURE_OPTIONS+=("--enable-libtheora")

if ${NONFREE_AND_GPL}; then

  if build "fdk_aac" "2.0.3"; then

    download "https://downloads.sourceforge.net/project/opencore-amr/fdk-aac/fdk-aac-${CURRENT_PACKAGE_VERSION}.tar.gz" "fdk-aac-${CURRENT_PACKAGE_VERSION}.tar.gz"

    execute ./configure --prefix="${WORKSPACE}" --disable-shared --enable-static --enable-pic
    execute make -j ${MJOBS}
    execute make install

    build_done "fdk_aac" "${CURRENT_PACKAGE_VERSION}"
  fi

  CONFIGURE_OPTIONS+=("--enable-libfdk-aac")
fi

##
## image library
##

if [[ ! "${TARGET_OS}" == "debian" ]]; then

  if build "libtiff" "4.7.0"; then

    download "https://download.osgeo.org/libtiff/tiff-${CURRENT_PACKAGE_VERSION}.tar.xz"

    execute ./configure --prefix="${WORKSPACE}" --disable-shared --enable-static --disable-dependency-tracking --disable-lzma --disable-webp --disable-zstd --without-x
    execute make -j ${MJOBS}
    execute make install

    build_done "libtiff" "${CURRENT_PACKAGE_VERSION}"
  fi
fi

if ! isLinux; then

  if build "libpng" "1.6.48"; then

    download "https://downloads.sourceforge.net/project/libpng/libpng16/${CURRENT_PACKAGE_VERSION}/libpng-${CURRENT_PACKAGE_VERSION}.tar.gz" "libpng-${CURRENT_PACKAGE_VERSION}.tar.gz"

    export LDFLAGS="${LDFLAGS}"
    export CPPFLAGS="${CFLAGS}"
    execute ./configure --prefix="${WORKSPACE}" --disable-shared --enable-static
    execute make -j ${MJOBS}
    execute make install

    build_done "libpng" "${CURRENT_PACKAGE_VERSION}"
  fi

  if build "libwebp" "1.5.0"; then

    download "https://storage.googleapis.com/downloads.webmproject.org/releases/webp/libwebp-${CURRENT_PACKAGE_VERSION}.tar.gz" "libwebp-${CURRENT_PACKAGE_VERSION}.tar.gz"

    # libwebp can fail to compile on Ubuntu if these flags were left set to CFLAGS
    CPPFLAGS=
    make_dir build
    cd build || exit
    execute cmake -DCMAKE_INSTALL_PREFIX="${WORKSPACE}" -DCMAKE_INSTALL_LIBDIR=lib -DCMAKE_INSTALL_BINDIR=bin -DCMAKE_INSTALL_INCLUDEDIR=include -DENABLE_SHARED=OFF -DENABLE_STATIC=ON -DWEBP_BUILD_CWEBP=OFF -DWEBP_BUILD_DWEBP=OFF -DWEBP_BUILD_GIF2WEBP=OFF -DWEBP_BUILD_IMG2WEBP=OFF -DWEBP_BUILD_VWEBP=OFF ../
    execute make -j ${MJOBS}
    execute make install

    build_done "libwebp" "${CURRENT_PACKAGE_VERSION}"
  fi
fi

CONFIGURE_OPTIONS+=("--enable-libwebp")

##
## other library
##

if [[ ! "${TARGET_OS}" == "debian" ]]; then

  if build "libsdl" "2.32.8"; then

    download "https://github.com/libsdl-org/SDL/releases/download/release-${CURRENT_PACKAGE_VERSION}/SDL2-${CURRENT_PACKAGE_VERSION}.tar.gz"

    execute ./configure --prefix="${WORKSPACE}" --disable-shared --enable-static
    execute make -j ${MJOBS}
    execute make install

    build_done "libsdl" "${CURRENT_PACKAGE_VERSION}"
  fi
fi

if ${NONFREE_AND_GPL}; then

  if build "srt" "1.5.4"; then

    download "https://github.com/Haivision/srt/archive/v${CURRENT_PACKAGE_VERSION}.tar.gz" "srt-${CURRENT_PACKAGE_VERSION}.tar.gz"

    export OPENSSL_ROOT_DIR="${WORKSPACE}"
    export OPENSSL_LIB_DIR="${WORKSPACE}"/lib
    export OPENSSL_INCLUDE_DIR="${WORKSPACE}"/include/

    if [[ "${TARGET_OS}" == "raspbian" ]]; then

      SRT_BUILD_FLAGS="-DATOMIC_USE_SRT_SYNC_MUTEX=ON"
    fi

    execute cmake . -DCMAKE_INSTALL_PREFIX="${WORKSPACE}" -DCMAKE_INSTALL_LIBDIR=lib -DCMAKE_INSTALL_BINDIR=bin -DCMAKE_INSTALL_INCLUDEDIR=include -DENABLE_SHARED=OFF -DENABLE_STATIC=ON -DENABLE_APPS=OFF -DUSE_STATIC_LIBSTDCXX=ON ${SRT_BUILD_FLAGS}
    execute make install

    if [ -n "${LDEXEFLAGS}" ]; then

      sed -i.backup 's/-lgcc_s/-lgcc_eh/g' "${WORKSPACE}"/lib/pkgconfig/srt.pc # The -i.backup is intended and required on macOS: https://stackoverflow.com/questions/5694228/sed-in-place-flag-that-works-both-on-mac-bsd-and-linux
    fi

    build_done "srt" "${CURRENT_PACKAGE_VERSION}"
  fi

  CONFIGURE_OPTIONS+=("--enable-libsrt")
fi

##
## HWaccel library
##

if isLinux && [[ "${TARGET_ARCH}" == "x86_64" ]]; then

#  Unfortunately, libva is broken in static builds of FFmpeg, making QSV out of reach for the time being.
#  # Intel QSV support.
#  if build "oneVPL" "v2023.3.1"; then
#
#    download "https://github.com/oneapi-src/oneVPL/archive/refs/tags/v2023.3.1.tar.gz" "oneVPL-v2023.3.1.tar.gz"
#
#    make_dir build
#    cd build || exit
#
#    execute cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="${WORKSPACE}" -DCMAKE_INSTALL_BINDIR=bin -DCMAKE_INSTALL_LIBDIR=lib \
#      -DBUILD_DISPATCHER=ON -DBUILD_DEV=ON -DBUILD_PREVIEW=OFF -DBUILD_TOOLS=OFF -DBUILD_TOOLS_ONEVPL_EXPERIMENTAL=OFF -DINSTALL_EXAMPLE_CODE=OFF \
#      -DBUILD_SHARED_LIBS=OFF -DBUILD_TESTS=OFF ..
#    execute cmake --build . --config Release
#    execute cmake --build . --config Release --target install
#
#    build_done "oneVPL" "v2023.3.1"
#  fi
#
#  CONFIGURE_OPTIONS+=("--enable-libvpl")
#
#  # Libva support.
#  if build "libva" "latest"; then
#
#    download "https://github.com/intel/libva/archive/refs/tags/2.20.0.tar.gz" "libva-2.20.0.tar.gz"
#
#    execute env LIBTOOLIZE="${WORKSPACE}/bin/libtoolize" ./autogen.sh --prefix="${WORKSPACE}" --with-drivers-path="/usr/lib/x86_64-linux-gnu/dri" --enable-static --disable-shared
#    execute make -j ${MJOBS}
#    execute make install
#
#    build_done "libva" "2.20.0"
#  fi
#
#  CONFIGURE_OPTIONS+=("--enable-vaapi")

  if command_exists "nvcc"; then

    if build "nv-codec" "11.1.5.2"; then

      download "https://github.com/FFmpeg/nv-codec-headers/releases/download/n11.1.5.2/nv-codec-headers-11.1.5.2.tar.gz"

      execute make PREFIX="${WORKSPACE}"
      execute make PREFIX="${WORKSPACE}" install

      build_done "nv-codec" "11.1.5.2"
    fi

    CFLAGS+=" -I/usr/local/cuda/include"
    LDFLAGS+=" -L/usr/local/cuda/lib64"
    CONFIGURE_OPTIONS+=("--enable-cuda-nvcc" "--enable-cuvid" "--enable-nvdec" "--enable-nvenc" "--enable-cuda-llvm" "--enable-ffnvcodec")

    if [ -z "${LDEXEFLAGS}" ]; then

      CONFIGURE_OPTIONS+=("--enable-libnpp") # Only libnpp cannot be statically linked.
    fi

    # https://arnon.dk/matching-sm-architectures-arch-and-gencode-for-various-nvidia-cards/
    CONFIGURE_OPTIONS+=("--nvccflags=-gencode arch=compute_52,code=sm_52")
  else

    CONFIGURE_OPTIONS+=("--disable-ffnvcodec")
  fi

  # Vaapi doesn't work well with static links FFmpeg.
  if [ -z "${LDEXEFLAGS}" ]; then

    # If the libva development SDK is installed, enable vaapi.
    if library_exists "libva"; then

      if build "vaapi" "1"; then

        build_done "vaapi" "1"
      fi

      CONFIGURE_OPTIONS+=("--enable-vaapi")
    fi
  fi

  if build "amf" "1.4.36"; then

    download "https://github.com/GPUOpen-LibrariesAndSDKs/AMF/archive/refs/tags/v${CURRENT_PACKAGE_VERSION}.tar.gz" "AMF-${CURRENT_PACKAGE_VERSION}.tar.gz" "AMF-${CURRENT_PACKAGE_VERSION}"

    execute rm -rf "${WORKSPACE}/include/AMF"
    execute mkdir -p "${WORKSPACE}/include/AMF"
    execute cp -r "${PACKAGES}"/AMF-${CURRENT_PACKAGE_VERSION}/AMF-${CURRENT_PACKAGE_VERSION}/amf/public/include/* "${WORKSPACE}/include/AMF/"

    build_done "amf" "${CURRENT_PACKAGE_VERSION}"
  fi

  CONFIGURE_OPTIONS+=("--enable-amf")
fi

##
## FFmpeg
##

# FFmpeg version to build if one isn't specified for us.
if [ -z "${FFMPEG_VERSION}" ]; then

  FFMPEG_VERSION="8.0"
fi

if [ -z "${EXTRA_VERSION:-}" ]; then

  EXTRA_VERSION="homebridge-${TARGET_OS}-${TARGET_ARCH}"

  if [ -n "${LDEXEFLAGS}" ]; then

    EXTRA_VERSION+="-static"
  fi
fi

if [ -d "${CWD}/.git" ]; then

  echo -e "\nTemporarily moving .git dir to .git.bak to workaround ffmpeg build bug" #causing ffmpeg version number to be wrong
  mv "${CWD}/.git" "${CWD}/.git.bak"
  # if build fails below, .git will remain in the wrong place...
fi

build "ffmpeg" "${FFMPEG_VERSION}"

download "https://ffmpeg.org/releases/ffmpeg-${FFMPEG_VERSION}.tar.gz" "FFmpeg-release-${FFMPEG_VERSION}.tar.gz"

# shellcheck disable=SC2086
echo ./configure "${CONFIGURE_OPTIONS[@]}" \
  --disable-debug \
  --disable-shared \
  --enable-pthreads \
  --enable-static \
  --enable-version3 \
  --extra-cflags="${CFLAGS}" \
  --extra-ldexeflags="${LDEXEFLAGS}" \
  --extra-ldflags="${LDFLAGS}" \
  --extra-libs="${EXTRALIBS}" \
  --pkgconfigdir="${WORKSPACE}/lib/pkgconfig" \
  --pkg-config-flags="--static" \
  --prefix="${WORKSPACE}" \
  --extra-version="${EXTRA_VERSION}"

./configure "${CONFIGURE_OPTIONS[@]}" \
  --disable-debug \
  --disable-shared \
  --enable-pthreads \
  --enable-static \
  --enable-version3 \
  --extra-cflags="${CFLAGS}" \
  --extra-ldexeflags="${LDEXEFLAGS}" \
  --extra-ldflags="${LDFLAGS}" \
  --extra-libs="${EXTRALIBS}" \
  --pkgconfigdir="${WORKSPACE}/lib/pkgconfig" \
  --pkg-config-flags="--static" \
  --prefix="${WORKSPACE}" \
  --extra-version="${EXTRA_VERSION}"

execute make -j ${MJOBS}
execute make install

if [ -d "${CWD}/.git.bak" ]; then

  mv "${CWD}/.git.bak" "${CWD}/.git"
fi

INSTALL_FOLDER="/usr"  # not recommended, overwrites system ffmpeg package
if [[ "${TARGET_OS}" == "darwin" ]]; then

  INSTALL_FOLDER="/usr/local"
else

  if [ -d "${HOME}/.local" ]; then  # systemd-standard user path

    INSTALL_FOLDER="${HOME}/.local"
  elif [ -d "/usr/local" ]; then

    INSTALL_FOLDER="/usr/local"
  fi
fi

verify_binary_type

echo ""
echo "Building done. The following binaries can be found here:"
echo "- ffmpeg: ${WORKSPACE}/bin/ffmpeg"

if ! contains "--disable-ffprobe" "${CONFIGURE_OPTIONS[@]}"; then

  echo "- ffprobe: ${WORKSPACE}/bin/ffprobe"
fi

if ! contains "--disable-ffplay" "${CONFIGURE_OPTIONS[@]}"; then

  echo "- ffplay: ${WORKSPACE}/bin/ffplay"
fi

echo ""

INSTALL_NOW=0
if [[ "${AUTOINSTALL}" == "yes" ]]; then

  INSTALL_NOW=1
elif [[ ! "${SKIPINSTALL}" == "yes" ]]; then

  read -r -p "Install these binaries to your ${INSTALL_FOLDER} folder? Existing binaries will be replaced. [Y/n] " response

  case $response in

    "" | [yY][eE][sS] | [yY])
      INSTALL_NOW=1
    ;;

  esac
fi

if [ "${INSTALL_NOW}" = 1 ]; then

  if command_exists "sudo" && [[ ${INSTALL_FOLDER} == /usr* ]]; then

    SUDO=sudo
  fi

  ${SUDO} cp "${WORKSPACE}/bin/ffmpeg" "${INSTALL_FOLDER}/bin/ffmpeg"

  if ! contains "--disable-ffprobe" "${CONFIGURE_OPTIONS[@]}"; then

    ${SUDO} cp "${WORKSPACE}/bin/ffprobe" "${INSTALL_FOLDER}/bin/ffprobe"
  fi

  if ! contains "--disable-ffplay" "${CONFIGURE_OPTIONS[@]}"; then

    ${SUDO} cp "${WORKSPACE}/bin/ffplay" "${INSTALL_FOLDER}/bin/ffplay"
  fi

  if [ ${MANPAGES} = 1 ]; then

    ${SUDO} mkdir -p "${INSTALL_FOLDER}/share/man/man1"
    ${SUDO} cp "${WORKSPACE}/share/man/man1"/ff* "${INSTALL_FOLDER}/share/man/man1"
    if command_exists "mandb"; then

      ${SUDO} mandb -q
    fi
  fi

  echo "Done. FFmpeg is now installed to your system."
fi

exit 0
