ARG BASE_IMAGE
FROM ${BASE_IMAGE:-library/alpine:3.11.3}

COPY qemu /usr/bin/

RUN apk add curl g++ gcc make python perl linux-headers bash diffutils tar

COPY build-ffmpeg /

ENV SKIPINSTALL=yes VERBOSE=yes

VOLUME /build
WORKDIR /build

CMD /build-ffmpeg --build

