ARG BASE_IMAGE
FROM ${BASE_IMAGE:-balenalib/raspberry-pi-debian:stretch}

COPY qemu /usr/bin/

RUN apt-get update && apt-get install -y build-essential curl g++ autoconf

COPY build-ffmpeg /

ENV SKIPINSTALL=yes VERBOSE=yes

VOLUME /build
WORKDIR /build

CMD /build-ffmpeg --build