#!/bin/sh
#
# Copyright 2023, The Homebridge Team.
# prepare-build: Prepare a docker image with the requisite packages to build an FFmpeg binary.
#

# Error out if we encounter issues.
set -e

# Pull in the OS release information from a given Linux environment. This allows us to distinguish between various Linux distributions.
. /etc/os-release

# echo `cat /etc/os-release`

# Install the dependencies needed to build FFmpeg on a supported Linux distribution.
case $ID in 

  alpine)
    echo "Configuring the Alpine Linux build environment."
    apk add autoconf automake bash cmake curl diffutils g++ gcc giflib-static git lame-dev libdrm-dev libogg-static libpng-static libtheora-dev libtheora-static libtool libvorbis-dev libvorbis-static linux-headers m4 make meson nasm opencore-amr-dev openssl-dev openssl-libs-static pcre-dev perl python3 samurai tar xz yasm zlib-dev zlib-static
    ;;

esac

